#!/usr/bin/env python3
"""
Repackage this skill for Google Gemini's "Gem" (custom Gem) format.

Why this exists:
A Gem takes one block of instructions plus a *small* number of knowledge
files — far fewer than the ~20 reference files this skill ships as. Uploading
them one by one fails. So this script folds every reference into a handful of
bundles, and writes the instruction text separately.

Two layouts are produced, because the per-Gem file limit differs by plan and
changes over time:

    dist/gem/split/   7 knowledge files, grouped by topic (preferred)
    dist/gem/single/  1 knowledge file containing everything (fallback)

Both carry identical content. Each embedded document keeps its original path in
its heading, so the cross-references already written inside the documents
("`references/simple/juice-and-feel.md` を読む") still resolve — the model finds
the heading by name instead of opening a file.

Usage:
    python3 scripts/build_gem.py
"""
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "dist" / "gem"

# (output file, human title, [source paths in order])
BUNDLES = [
    ("01-router-and-principles.md", "ルーターと原則（本体）", [
        "SKILL.md",
    ]),
    ("02-core-theory.md", "理論・ジャンル別パターン・複数人・実証データ", [
        "references/core/theory.md",
        "references/core/genre-patterns.md",
        "references/core/multiplayer-sync.md",
        "references/core/case-studies-and-metrics.md",
    ]),
    ("03-feel-and-simple.md", "極小ゲームの物理・手触り・生成", [
        "references/simple/mechanics-and-physics.md",
        "references/simple/juice-and-feel.md",
        "references/simple/procedural-generation.md",
        "references/simple/one-button-runner.md",
        "references/simple/canon.md",
    ]),
    ("04-audio-and-rhythm.md", "音・リズム・共感覚", [
        "references/core/rhythm-and-synesthesia.md",
        "references/audio/web-audio-patterns.md",
        "references/audio/dynamic-music.md",
        "references/audio/ai-and-procedural.md",
        "references/audio/platform-and-frameworks.md",
    ]),
    ("05-input-and-camera.md", "入力の抽象化とカメラ入力", [
        "references/core/input-layer.md",
        "references/core/camera-input.md",
    ]),
    ("06-beauty-and-projection.md", "静かで美しい体験・不可能幾何・美術", [
        "references/core/calm-experience.md",
        "references/core/projection-as-rule.md",
        "references/art-pipeline.md",
    ]),
    ("07-tech-workflows-code.md", "技術選定・手順書・動く実装", [
        "references/web-stack.md",
        "workflows/mechanic-design-pipeline.md",
        "workflows/intuition-audit.md",
        "workflows/playtest-card-orid.md",
        "assets/juice-controller.js",
        "assets/chunk-generator.js",
        "assets/audio-engine.js",
        "assets/sfx-library.js",
    ]),
]

BUNDLE_HEADER = """<!-- Generated by scripts/build_gem.py — do not edit by hand. -->
# {title}

これは「直感的ゲームデザイン」スキルの一部です。**下の各節は、元は別々のファイルでした。**
節の見出しにある `パス` が元のファイル名です。文中に `references/...` のようなファイル参照が
出てきたら、それは**このナレッジ群の中の、その名前を持つ節**を指します。開くファイルはありません。

---
"""

SINGLE_HEADER = """<!-- Generated by scripts/build_gem.py — do not edit by hand. -->
# 直感的ゲームデザイン — 全リファレンス（単一ファイル版）

説明書なしで理解できるゲーム／インタラクティブ体験を、設計・手触り・音・技術まで作るための資料一式。

**各節の見出しにある `パス` が、元のファイル名です。** 文中に `references/...` のようなファイル参照が
出てきたら、それは**この文書内の、その名前を持つ節**を指します。開く外部ファイルはありません。

---
"""


def strip_front_matter(text):
    """SKILL.md の YAML front matter を外し、description を別に返す。"""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return text, ""
    desc = ""
    dm = re.search(r"^description:\s*(.+)$", m.group(1), re.M)
    if dm:
        desc = dm.group(1).strip()
    return text[m.end():], desc


def embed(path):
    """1ファイルを、元のパスを見出しに持つ節として整形する。"""
    raw = (ROOT / path).read_text(encoding="utf-8")
    if path == "SKILL.md":
        raw, _ = strip_front_matter(raw)
    if path.endswith(".js"):
        return f"\n\n---\n\n## `{path}`\n\n```javascript\n{raw.rstrip()}\n```\n"

    # 元の H1 は節見出しへ畳む。残すと「見出しが2つ並ぶ」形になって読みにくい
    title = ""
    m = re.match(r"^# (.+)\n+", raw)
    if m:
        title = m.group(1).strip()
        raw = raw[m.end():]
    # 見出しレベルを1段下げ、束ねた時に階層が崩れないようにする
    body = re.sub(r"^(#{1,5}) ", r"#\1 ", raw, flags=re.M)
    head = f"## `{path}` — {title}" if title else f"## `{path}`"
    return f"\n\n---\n\n{head}\n\n{body}\n"


def tracked():
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True,
                         text=True, check=True).stdout.split()
    return set(out)


def main():
    files = tracked()
    listed = {p for _, _, srcs in BUNDLES for p in srcs}
    missing = sorted(p for p in listed if p not in files)
    if missing:
        sys.exit(f"BUNDLES references files not in git: {missing}")

    # バンドルから漏れた参照資料が無いかを検査する。
    # 漏れると「Gem版にだけ無い章」が静かに生まれ、そのことに誰も気づけない。
    should_bundle = {
        f for f in files
        if (f.startswith(("references/", "workflows/", "assets/")) or f == "SKILL.md")
    }
    dropped = sorted(should_bundle - listed)
    if dropped:
        sys.exit(f"これらがどのバンドルにも入っていません: {dropped}")

    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "split").mkdir(parents=True)
    (OUT / "single").mkdir(parents=True)

    single_parts = [SINGLE_HEADER]
    report = []

    for name, title, srcs in BUNDLES:
        parts = [BUNDLE_HEADER.format(title=title)]
        for p in srcs:
            section = embed(p)
            parts.append(section)
            single_parts.append(section)
        text = "".join(parts)
        (OUT / "split" / name).write_text(text, encoding="utf-8")
        report.append((name, len(text)))

    single = "".join(single_parts)
    (OUT / "single" / "intuitive-game-design-all.md").write_text(single, encoding="utf-8")

    # 指示文（Gem の Instructions 欄に貼る本文）は手書きで維持する
    src = ROOT / "gem" / "instructions.md"
    short = ROOT / "gem" / "instructions-short.md"
    setup = ROOT / "gem" / "SETUP.md"
    for f in (src, short, setup):
        if not f.exists():
            sys.exit(f"missing {f.relative_to(ROOT)} — 指示文は手書きで維持します")
        shutil.copy(f, OUT / f.name)

    print(f"{OUT.relative_to(ROOT)}/")
    print("  split/   （推奨：ナレッジ7ファイル）")
    for name, n in report:
        print(f"    {name:<32} {n:>7,} 文字")
    print(f"  single/  intuitive-game-design-all.md   {len(single):>7,} 文字")
    print()
    for f in (src, short):
        n = len(f.read_text(encoding="utf-8"))
        print(f"  {f.name:<26} {n:>7,} 文字  ← Instructions 欄に貼る")
    print(f"  SETUP.md                     手順書")


if __name__ == "__main__":
    main()
